-- MySQL Script generated by MySQL Workbench
-- Sun Oct 24 17:03:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `Address ID` INT NOT NULL,
  `State name` VARCHAR(45) NULL,
  `City name` VARCHAR(45) NULL,
  PRIMARY KEY (`Address ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `Department name` VARCHAR(45) NOT NULL,
  `Telephone number` BIGINT(24) NULL,
  PRIMARY KEY (`Department name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `Prof. ID` INT NOT NULL,
  `First name` VARCHAR(45) NULL,
  `Last name` VARCHAR(45) NULL,
  `Age` INT NULL,
  `Martital status` VARCHAR(45) NULL,
  `Research areas` VARCHAR(45) NOT NULL,
  `prof. dept_Department name` INT NOT NULL,
  PRIMARY KEY (`Prof. ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `Stud. ID` INT NOT NULL,
  `First name` VARCHAR(45) NULL,
  `Last name` VARCHAR(45) NULL,
  `Age` INT NULL,
  `Sex` ENUM("Male", "Female") NULL,
  `Address_Address ID` INT NOT NULL,
  `Department_Department name` VARCHAR(45) NOT NULL,
  `Passed_grade` INT NOT NULL,
  `Professor_Prof. ID` INT NOT NULL,
  PRIMARY KEY (`Stud. ID`),
  INDEX `fk_Student_Address1_idx` (`Address_Address ID` ASC) VISIBLE,
  INDEX `fk_Student_Department1_idx` (`Department_Department name` ASC) VISIBLE,
  INDEX `fk_Student_Professor1_idx` (`Professor_Prof. ID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Address1`
    FOREIGN KEY (`Address_Address ID`)
    REFERENCES `mydb`.`Address` (`Address ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Department1`
    FOREIGN KEY (`Department_Department name`)
    REFERENCES `mydb`.`Department` (`Department name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Professor1`
    FOREIGN KEY (`Professor_Prof. ID`)
    REFERENCES `mydb`.`Professor` (`Prof. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Graduate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Graduate` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Graduate` (
  `GPA` DOUBLE NOT NULL,
  `Student_Stud. ID` INT NOT NULL,
  `Research areas` VARCHAR(45) NOT NULL,
  `Professor_Prof. ID` INT NOT NULL,
  PRIMARY KEY (`GPA`, `Student_Stud. ID`),
  INDEX `fk_Graduate_Student_idx` (`Student_Stud. ID` ASC) VISIBLE,
  INDEX `fk_Graduate_Professor1_idx` (`Professor_Prof. ID` ASC) VISIBLE,
  CONSTRAINT `fk_Graduate_Student`
    FOREIGN KEY (`Student_Stud. ID`)
    REFERENCES `mydb`.`Student` (`Stud. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Graduate_Professor1`
    FOREIGN KEY (`Professor_Prof. ID`)
    REFERENCES `mydb`.`Professor` (`Prof. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dean's List`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dean's List` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dean's List` (
  `Year` INT NOT NULL,
  `Semester` ENUM('Spring', "Summer", "Fall", "Winter") NOT NULL,
  `Scholarship` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Year`, `Semester`, `Scholarship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classroom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classroom` (
  `Building name` VARCHAR(45) NOT NULL,
  `Room number` INT NULL,
  PRIMARY KEY (`Building name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `Course code` INT NOT NULL,
  `Year` INT NOT NULL,
  `Semester` ENUM('Spring', "Summer", "Fall", "Winter") NOT NULL,
  `course name` VARCHAR(45) NULL,
  `credit` INT NULL,
  `Lecture day` DATE NULL,
  `Start time` TIME NULL,
  `Duration` TIME NULL,
  `classroom_Building name` VARCHAR(45) NOT NULL,
  `Professor_Prof. ID` INT NOT NULL,
  PRIMARY KEY (`Course code`, `Year`, `Semester`, `Professor_Prof. ID`),
  INDEX `fk_Course_classroom1_idx` (`classroom_Building name` ASC) VISIBLE,
  INDEX `fk_Course_Professor1_idx` (`Professor_Prof. ID` ASC) VISIBLE,
  CONSTRAINT `fk_Course_classroom1`
    FOREIGN KEY (`classroom_Building name`)
    REFERENCES `mydb`.`classroom` (`Building name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Professor1`
    FOREIGN KEY (`Professor_Prof. ID`)
    REFERENCES `mydb`.`Professor` (`Prof. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Papers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Papers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Papers` (
  `Paper code` INT NOT NULL,
  `Paper title` VARCHAR(45) NULL,
  PRIMARY KEY (`Paper code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_has_Dean's List`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student_has_Dean's List` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student_has_Dean's List` (
  `Student_Stud. ID` INT NOT NULL,
  `Dean's List_Year` INT NOT NULL,
  `Dean's List_Semester` ENUM('Spring', "Summer", "Fall", "Winter") NOT NULL,
  `Dean's List_Scholarship` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Student_Stud. ID`, `Dean's List_Year`, `Dean's List_Semester`, `Dean's List_Scholarship`),
  INDEX `fk_Student_has_Dean's List_Dean's List1_idx` (`Dean's List_Year` ASC, `Dean's List_Semester` ASC, `Dean's List_Scholarship` ASC) VISIBLE,
  INDEX `fk_Student_has_Dean's List_Student1_idx` (`Student_Stud. ID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Dean's List_Student1`
    FOREIGN KEY (`Student_Stud. ID`)
    REFERENCES `mydb`.`Student` (`Stud. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Dean's List_Dean's List1`
    FOREIGN KEY (`Dean's List_Year` , `Dean's List_Semester` , `Dean's List_Scholarship`)
    REFERENCES `mydb`.`Dean's List` (`Year` , `Semester` , `Scholarship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Past Residence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Past Residence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Past Residence` (
  `Student_Stud. ID` INT NOT NULL,
  `Address_Address ID` INT NOT NULL,
  `Lived yeara` INT NOT NULL,
  INDEX `fk_Past Residence_Student1_idx` (`Student_Stud. ID` ASC) VISIBLE,
  INDEX `fk_Past Residence_Address1_idx` (`Address_Address ID` ASC) VISIBLE,
  PRIMARY KEY (`Student_Stud. ID`),
  CONSTRAINT `fk_Past Residence_Student1`
    FOREIGN KEY (`Student_Stud. ID`)
    REFERENCES `mydb`.`Student` (`Stud. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Past Residence_Address1`
    FOREIGN KEY (`Address_Address ID`)
    REFERENCES `mydb`.`Address` (`Address ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prof. dept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prof. dept` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prof. dept` (
  `Department phone number` VARCHAR(45) NULL,
  `Professor_Prof. ID` INT NOT NULL,
  `Department_Department name` VARCHAR(45) NOT NULL,
  INDEX `fk_prof. dept_Professor1_idx` (`Professor_Prof. ID` ASC) VISIBLE,
  PRIMARY KEY (`Professor_Prof. ID`),
  INDEX `fk_prof. dept_Department1_idx` (`Department_Department name` ASC) VISIBLE,
  CONSTRAINT `fk_prof. dept_Professor1`
    FOREIGN KEY (`Professor_Prof. ID`)
    REFERENCES `mydb`.`Professor` (`Prof. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prof. dept_Department1`
    FOREIGN KEY (`Department_Department name`)
    REFERENCES `mydb`.`Department` (`Department name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Graduate_has_Papers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Graduate_has_Papers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Graduate_has_Papers` (
  `Graduate_GPA` DOUBLE NOT NULL,
  `Graduate_Student_Stud. ID` INT NOT NULL,
  `Papers_Paper code` INT NOT NULL,
  PRIMARY KEY (`Graduate_GPA`, `Graduate_Student_Stud. ID`, `Papers_Paper code`),
  INDEX `fk_Graduate_has_Papers_Papers1_idx` (`Papers_Paper code` ASC) VISIBLE,
  INDEX `fk_Graduate_has_Papers_Graduate1_idx` (`Graduate_GPA` ASC, `Graduate_Student_Stud. ID` ASC) VISIBLE,
  CONSTRAINT `fk_Graduate_has_Papers_Graduate1`
    FOREIGN KEY (`Graduate_GPA` , `Graduate_Student_Stud. ID`)
    REFERENCES `mydb`.`Graduate` (`GPA` , `Student_Stud. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Graduate_has_Papers_Papers1`
    FOREIGN KEY (`Papers_Paper code`)
    REFERENCES `mydb`.`Papers` (`Paper code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_has_Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Course_has_Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Course_has_Student` (
  `Course_Course code` INT NOT NULL,
  `Course_Year` INT NOT NULL,
  `Course_Semester` ENUM('Spring', "Summer", "Fall", "Winter") NOT NULL,
  `Course_Professor_Prof. ID` INT NOT NULL,
  `Student_Stud. ID` INT NOT NULL,
  `Grade` VARCHAR(3) NULL,
  PRIMARY KEY (`Course_Course code`, `Course_Year`, `Course_Semester`, `Course_Professor_Prof. ID`, `Student_Stud. ID`),
  INDEX `fk_Course_has_Student_Student1_idx` (`Student_Stud. ID` ASC) VISIBLE,
  INDEX `fk_Course_has_Student_Course1_idx` (`Course_Course code` ASC, `Course_Year` ASC, `Course_Semester` ASC, `Course_Professor_Prof. ID` ASC) VISIBLE,
  CONSTRAINT `fk_Course_has_Student_Course1`
    FOREIGN KEY (`Course_Course code` , `Course_Year` , `Course_Semester` , `Course_Professor_Prof. ID`)
    REFERENCES `mydb`.`Course` (`Course code` , `Year` , `Semester` , `Professor_Prof. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_has_Student_Student1`
    FOREIGN KEY (`Student_Stud. ID`)
    REFERENCES `mydb`.`Student` (`Stud. ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
